### PR TITLE
Closes #18: feature: Add WebSecurity to EUM Server

### LINKED ISSUE #18: [Feature] - Add WebSecurity to the EUM server using simple API token security
**Is your feature request related to a problem? Please describe.**
Currently, the EUM server does not support web security.

**Describe the solution you'd like**
As a first step, I'd like to be able to authenticate with simple API token security.

### PR DESCRIPTION
**Pull request by ClaudioWaldvogel**
Closes #18 

This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17)* status: all files reviewed, 2 unresolved discussions (waiting on @ClaudioWaldvogel)

___
*[`src/main/java/rocks/inspectit/oce/eum/server/configuration/model/security/authProvider/SimpleApiTokenAuthenticationProviderSettings.java` line 43 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17#-NHcKTUl4yAMzv5_B4sP:-NHcKTUl4yAMzv5_B4sQ:bhiy8lm) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/6065be4ab0a788a24ca7af771becad646c854cb3/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/security/authProvider/SimpleApiTokenAuthenticationProviderSettings.java#L43)):*
> ```Java
>     private String defaultFileName;
> 
>     private boolean createDefaultFileIfNotExists = true;
> ```

why do we need the boolean?
Wouldn't it be sufficient to check if `defaultFileName` is not empty? 

As far as I can see, `defaultFileName` is only used in `SimpleApiAuthenticationProvider#createDefaultTokenProviderFile`.

What happens if `defaultFileName` is set but `createDefaultFileIfNotExists=false`?
___
*[`src/main/java/rocks/inspectit/oce/eum/server/utils/DirectoryPoller.java` line 68 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17#-NHcJJry7OFAT8K6kgR-:-NHcJJry7OFAT8K6kgR0:b-rfdicg) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/6065be4ab0a788a24ca7af771becad646c854cb3/src/main/java/rocks/inspectit/oce/eum/server/utils/DirectoryPoller.java#L68)):*
> ```Java
>      * Flag to indicate that we need to shutdown the used executor on destroy.
>      */
>     private boolean isDefaultExecutor = false;
> ```

Shouldn't it rather say 
`Flag to indicate that the {@link #defaultExecutor()} is executed, which needs to be shut down on destroy`?
___
*[`src/main/java/rocks/inspectit/oce/eum/server/utils/DirectoryPoller.java` line 97 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17#-NHcJpv17XXIVHQzXhlN:-NHcJpv2BoUKssHtC1Vo:b7u0dty) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/6065be4ab0a788a24ca7af771becad646c854cb3/src/main/java/rocks/inspectit/oce/eum/server/utils/DirectoryPoller.java#L97)):*
> ```Java
> 
>     public DirectoryPoller start() {
>         pollingTask = executor.scheduleWithFixedDelay(this::pollChanges, frequencyInMillis, frequencyInMillis, TimeUnit.MILLISECONDS);
> ```

should we start with an initial delay of `frequencyInMillis` or start immediately?

**Review by MariusBrill — APPROVED** [review]
> Reviewed 7 of 19 files at r1, 2 of 6 files at r2, 1 of 6 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17)* status: all files reviewed, 2 unresolved discussions (waiting on @ClaudioWaldvogel)

**Review by MariusBrill — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17)* status: all files reviewed, 2 unresolved discussions (waiting on @ClaudioWaldvogel)

**Review by MariusBrill — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17)* status: all files reviewed, 2 unresolved discussions (waiting on @ClaudioWaldvogel)

**Review by heiko-holz — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ClaudioWaldvogel)

**Pull request merged**
