### PR TITLE
Update changelog generator action to fix deprecated warning

### LINKED ISSUE #37: [Feature] - Fix 'set-output' warning when generating changelog
Fix 'set-output' warning when generating changelog.
See [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](url)

### PR DESCRIPTION
**Pull request by danipaniii**
Closes #37

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38)

### CODE REVIEW

**Review by quandor — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @danipaniii)

___
*[`.github/workflows/eumserver_release.yml` line 17 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38#-NSBdTV79EDQ1WsRou82:-NSBdTV79EDQ1WsRou83:b-kaase2) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/6874480cf4d9048037af0eeefc822938c7442e25/.github/workflows/eumserver_release.yml#L17)):*
> ```YAML
>     needs: [test_eum_server]
>     steps:
>     - name: Checkout code
> ```

I am not sure, that this indentation is correct. AFAIK list items in yaml need to be indented a level.

**Review by quandor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38)* status: all files reviewed, 1 unresolved discussion (waiting on @danipaniii)

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @quandor)

___
*[`.github/workflows/eumserver_release.yml` line 17 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38#-NSBdTV79EDQ1WsRou82:-NSBfP7l8xDX5pY920U2:b-bdcc24) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/6874480cf4d9048037af0eeefc822938c7442e25/.github/workflows/eumserver_release.yml#L17)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

I am not sure, that this indentation is correct. AFAIK list items in yaml need to be indented a level.
</blockquote></details>

I forgot to save it with disabling the auto-fromat by vs code. I fixed it.

**Review by quandor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/38#-:-NSKKD9a8vSK4np-eF0T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

**Pull request merged**
