### PR TITLE
Closes #28 Changelog Config fails to get fetched

### LINKED ISSUE #28: [Bug] - Changelog Config fails to get fetched
**Describe the bug**
The config for the changelog does not get fetched by the github action, thus using the default config.

**Expected behavior**
The changelog config gets fetched

**Additional information (screenshots, stack traces, etc.)**
image

**Additional context**
The changelog is supposed to be created automatically when creating a release, but when doing a release it is failing to generate a proper  changelog at the moment.

### PR DESCRIPTION
**Pull request by danipaniii**
Closes #28 
With this PR, the config file for the changelog gets fetched and the changelog gets generated properly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29)* status: all files reviewed, 3 unresolved discussions (waiting on @danipaniii)

___
*[`.github/workflows/eumserver-release-config.json` line 4 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29#-NN6iU2XDoqzcpEh54eb:-NN6iU2XDoqzcpEh54ec:bmttors) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ce4c8bfedaf24d98f2cb6cc8b2b2a86b6dbfd2d3/.github/workflows/eumserver-release-config.json#L4)):*
> ```JSON
>     "categories": [
>         {
>             "title": "## 🛠 Breaking Changs",
> ```

Let's try to be consistent in the changelog of the agent and the eum-server.

We suggest the following:

* 🛠 Breaking Changes 
* 🚀 Implemented Enhancements
* 🐛 Bugfixes
* 🧪 Tests
* Other Changes

I don't care whether the icon before or after the text.

It would be great if you can commit the same changes to the PR https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NN6GHcU-0YyL4pKL0jl
___
*[`.github/workflows/eumserver-release-config.json` line 13 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29#-NN6inU3C2sKIMPaJJvc:-NN6inU3C2sKIMPaJJvd:b-yanxhi) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ce4c8bfedaf24d98f2cb6cc8b2b2a86b6dbfd2d3/.github/workflows/eumserver-release-config.json#L13)):*
> ```JSON
>         {
>             "title": "## 🐛 Fixes",
>             "labels": ["fix"]
> ```

Add "bug" as a label as well, as the issues will be labeled "bug" (and rarely "fix")
___
*[`.github/workflows/eumserver_release.yml` line 15 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29#-NN6jTQh0MOD7xjodyfV:-NN6jTQh0MOD7xjodyfW:b8ro9uu) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ce4c8bfedaf24d98f2cb6cc8b2b2a86b6dbfd2d3/.github/workflows/eumserver_release.yml#L15)):*
> ```YAML
>       name: Build and release EUM Server
>       runs-on: ubuntu-latest
>       needs: [test_eum_server] #test
> ```

do we need this comment here?
What does it mean?

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

___
*[`.github/workflows/eumserver-release-config.json` line 4 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29#-NN6iU2XDoqzcpEh54eb:-NNa9DQOBIKyAig0LuEN:b-896fix) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ce4c8bfedaf24d98f2cb6cc8b2b2a86b6dbfd2d3/.github/workflows/eumserver-release-config.json#L4)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Let's try to be consistent in the changelog of the agent and the eum-server.

We suggest the following:

* 🛠 Breaking Changes 
* 🚀 Implemented Enhancements
* 🐛 Bugfixes
* 🧪 Tests
* Other Changes

I don't care whether the icon before or after the text.

It would be great if you can commit the same changes to the PR https://reviewable.io/reviews/inspectit/inspectit-ocelot/1516#-NN6GHcU-0YyL4pKL0jl
</blockquote></details>

Done.
___
*[`.github/workflows/eumserver-release-config.json` line 13 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29#-NN6inU3C2sKIMPaJJvc:-NNa9EyH2A8xsLTgh07E:b-896fix) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ce4c8bfedaf24d98f2cb6cc8b2b2a86b6dbfd2d3/.github/workflows/eumserver-release-config.json#L13)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Add "bug" as a label as well, as the issues will be labeled "bug" (and rarely "fix")
</blockquote></details>

Done.
___
*[`.github/workflows/eumserver_release.yml` line 15 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29#-NN6jTQh0MOD7xjodyfV:-NNa9HWB0U5zioP_5rdT:borerv3) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ce4c8bfedaf24d98f2cb6cc8b2b2a86b6dbfd2d3/.github/workflows/eumserver_release.yml#L15)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we need this comment here?
What does it mean?
</blockquote></details>

I must have overlooked that comment. It is not needed and I removed it.

**Comment by danipaniii** [comment]
Also I believe it is important to mention, that in the changelog just the PRs tagged with at least one of the mentioned labels in the changelog config will be displayed in the changelog. 

Same goes for the PR: https://github.com/inspectIT/inspectit-ocelot/pull/1516

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/29)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

**Review by heiko-holz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

**Pull request merged**
