### PR TITLE
Move EUM-server to separate repo

### PR DESCRIPTION
**Pull request by aaronweissler**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1)

### CODE REVIEW

**Comment by aaronweissler** [comment]
Needs changes relating to EUM-server from https://github.com/inspectIT/inspectit-ocelot/pull/1375 as well

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1)* status: 0 of 114 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1#-N1wTLNk-k-toKeemD11:-N1wTLNk-k-toKeemD12:b-t3actk) (no related file):*
Needs changes relating to EUM-server from inspectIT/inspectit-ocelot#1375 as well

___

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1)* status: 0 of 116 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1#-N1wTLNk-k-toKeemD11:-N2BANTs9lG3Y0mPoTir:bzhhyp2) (no related file):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Needs changes relating to EUM-server from inspectIT/inspectit-ocelot#1375 as well
</blockquote></details>

Changes are added now.

___

**Review by heiko-holz — APPROVED** [review]
> Reviewed 105 of 114 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

___
*[`LICENSE` line 189 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1#-N3JRXMpAnZf1RbT8xff:-N3JRXMpAnZf1RbT8xfg:b-agvqk) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/f22c467a33228ef4753c3e611124e85f394fb378/LICENSE#L189)):*
> ```
>       identification within third-party archives.
> 
>    Copyright 2019 Novatec Consulting GmbH
> ```

is 2019 correct? or rather 2022?
Is this set automatically or manually?

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

___
*[`LICENSE` line 189 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/1#-N3JRXMpAnZf1RbT8xff:-N3JSqTE7g6VGQhWzjED:b-3zsiec) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/f22c467a33228ef4753c3e611124e85f394fb378/LICENSE#L189)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

is 2019 correct? or rather 2022?
Is this set automatically or manually?
</blockquote></details>

It was just set to "Copyright [yyyy] [name of copyright owner]" probably automatically by GitHub before. I then manually added the year and name. 
I'm not sure which year would be more appropriate. I simply copied the info from the inspectit-ocelot repo's license

**Pull request merged**
