### PR TITLE
Explains token file format in README

### PR DESCRIPTION
**Pull request by quandor**
This change is [Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26)* status: all files reviewed, 1 unresolved discussion (waiting on @quandor)

___
*[`README.md` line 285 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26#-NMYoiSp6hL_mh8QqfLJ:-NMYoiSp6hL_mh8QqfLK:b-zegh37) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ea7b64e0ba30beee89592b848d4b988dc13f33ae/README.md#L285)):*
> ```Markdown
> The format for the token files is as follows:
> ```yaml
>   # Allows grouping of tokens. E.g. you can document which application, person, organization, etc. knows about this token. It has no influence on security.
> ```

How can I understand the "grouping"?
I can't add multiple `token` to the same group, right?

**Review by quandor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`README.md` line 285 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26#-NMYoiSp6hL_mh8QqfLJ:-NMbtI3tBn4u5TLancYS:b-j9u9r2) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ea7b64e0ba30beee89592b848d4b988dc13f33ae/README.md#L285)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

How can I understand the "grouping"?
I can't add multiple `token` to the same group, right?
</blockquote></details>

You are right. _grouping_ is a misleading.  I rephrased that sentence.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @quandor)

___
*[`README.md` line 285 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26#-NMYoiSp6hL_mh8QqfLJ:-NMbuJBx2Rmt5zSLFJMU:b-xnndms) ([raw file](https://github.com/inspectIT/inspectit-ocelot-eum-server/blob/ea7b64e0ba30beee89592b848d4b988dc13f33ae/README.md#L285)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

You are right. _grouping_ is a misleading.  I rephrased that sentence.
</blockquote></details>

Perfect, thanks!

**Review by heiko-holz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot-eum-server/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quandor)

**Pull request merged**
