### PR TITLE
Add specific exception for missing SpanExporters in TraceController

### PR DESCRIPTION
**Pull request by aaronweissler**
Closes https://github.com/inspectIT/inspectit-ocelot-eum-server/issues/9

This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronweissler)

___
*[`src/main/java/rocks/inspectit/oce/eum/server/rest/TraceController.java` line 50 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7#-N3KVS5h2FG_HmzlMGNy:-N3KVS5h2FG_HmzlMGNz:bqbxfep) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/005a495c3aad68ffa722d2fd95f1f535b16f2d3d/src/main/java/rocks/inspectit/oce/eum/server/rest/TraceController.java#L50)):*
> ```Java
>         try {
>             if(spanExporters == null){
>                 log.warn("A span was sent to the EUM-server for processing but no SpanExporter exists.");
> ```

should we also specify the fix in the warning message or only in the exception?

E.g., 

`but no span exporter is registered enabled via inspectit-eum-server.tracing.jaeger (update inspectit-eum-server.exporters.tracing according, e.g., adding a configuration for Jaeger)`

Further question: does the EUM server allow anything else than Jaeger for exporting traces? If not, then we can directly tell that no Jaeger trace exporter is appropriately defined or enabled in the configuration (instead of using the generic `SpanExporter` termin).

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`src/main/java/rocks/inspectit/oce/eum/server/rest/TraceController.java` line 50 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7#-N3KVS5h2FG_HmzlMGNy:-N3NrX81DfxgD7aVj4df:bsyyx09) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/005a495c3aad68ffa722d2fd95f1f535b16f2d3d/src/main/java/rocks/inspectit/oce/eum/server/rest/TraceController.java#L50)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

should we also specify the fix in the warning message or only in the exception?

E.g., 

`but no span exporter is registered enabled via inspectit-eum-server.tracing.jaeger (update inspectit-eum-server.exporters.tracing according, e.g., adding a configuration for Jaeger)`

Further question: does the EUM server allow anything else than Jaeger for exporting traces? If not, then we can directly tell that no Jaeger trace exporter is appropriately defined or enabled in the configuration (instead of using the generic `SpanExporter` termin).
</blockquote></details>

I feel like it would be enough in most cases to only have it in the exception, but adding it to the warning log wouldn't hurt either, sure.

Right now there's only Jaeger. I tried to keep it general, since the way it is implemented implies there could be more added in the future. If the message only specifically mentioned Jaeger and new ones were added at some point, we would have to remember to update that log message too.

**Review by heiko-holz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronweissler)

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @aaronweissler)

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/7#-:-N3OAXE-2CKM7PtioPVn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Pull request merged**
