### PR TITLE
Closes #11 Adding Release CI/CD-Pipeline with Github Actions 

### LINKED ISSUE #11: Automate Release with CI/CD-Pipeline
Create a Release CI/CD-Pipeline with GithubActions.

### PR DESCRIPTION
**Pull request by danipaniii**
I implemented a Release CI/CD-Pipeline with Github Actions.
When pushing to the repository with a tag [0-9].[0-9].[0-9]* the the release event will be triggered. Generating a eumserver.jar, a eumserver.zip and eumserver.tar.gz.

The changelog gets generated automatically and can be configured via a .json file.
Finally it pushes a docker image to Dockerhub. At the moment I put in the details to my Dockerhub test-repo, since I don't know the credentials for the inspectit ocelot Dockerhub repo. This will have to be changed, before merge.

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)

### CODE REVIEW

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`.github/workflows/eumserver_release.yml` line 58 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NJe5R1N6InaWKL1zqCd:-NJe5R1O5nxDLuFX_BKS:b3esje6) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/2703eef1b51d68fb0e96db107ba17f655ae609fb/.github/workflows/eumserver_release.yml#L58)):*
> ```YAML
>         - name: Checkout
>           uses: actions/checkout@v3
>         - name: Download eumserver jar
> ```

The eumserver.jar doesn't seem to be downloaded properly.
Another option could also be, that it is being downloaded zipped and first needs to be unzipped. But when looking at the generated file structure in the docker image, there is no eumserver.jar or zip being found.
The entrypoint.sh file which gets succesfully added to the docker container still needs some rework to execute the jar with any version number attached to the end (inspectit-ocelot-eum-server-[0-9]*.[0-9]*.[0-9]*.jar)

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: 0 of 4 files reviewed, all discussions resolved

___
*[`.github/workflows/eumserver_release.yml` line 58 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NJe5R1N6InaWKL1zqCd:-NJzQ55uDBnjilYlYxAL:bt2vr1b) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/2703eef1b51d68fb0e96db107ba17f655ae609fb/.github/workflows/eumserver_release.yml#L58)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

The eumserver.jar doesn't seem to be downloaded properly.
Another option could also be, that it is being downloaded zipped and first needs to be unzipped. But when looking at the generated file structure in the docker image, there is no eumserver.jar or zip being found.
The entrypoint.sh file which gets succesfully added to the docker container still needs some rework to execute the jar with any version number attached to the end (inspectit-ocelot-eum-server-[0-9]*.[0-9]*.[0-9]*.jar)

</blockquote></details>

Fixed.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @danipaniii)

___
*[`.github/workflows/eumserver_release.yml` line 75 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKlmttVB4gTp0DviLI9:-NKlmttVB4gTp0DviLIA:b77kh26) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L75)):*
> ```YAML
>           uses: docker/login-action@v2
>           with:
>             username: ${{ secrets.DOCKER_USERNAME }}
> ```

As discussed, please change to `DOCKER_HUB_USER` and `DOCKER_HUB_PASSWORD`

**Review by danipaniii — COMMENTED** [review]
In a meeting we have also discussed to change the cyclonedx version to 1.7.2. However, when changing the version, the eum server resulted having build issues, so for the time being I left the version at 1.5.0 and added the Bom.json and Bom.xml to the artifacts.

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-:-NKm6PgD3flPSVpf_AjT:b-57bf7p)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`.github/workflows/eumserver_release.yml` line 75 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKlmttVB4gTp0DviLI9:-NKm6K7z7A_aghzl1EWJ:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L75)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

As discussed, please change to `DOCKER_HUB_USER` and `DOCKER_HUB_PASSWORD`
</blockquote></details>

Done.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @danipaniii)

___
*[`.github/workflows/eumserver-release-config.json` line 21 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmHNVp3g56qACiSEs3:-NKmHNVp3g56qACiSEs4:bcaf6ts) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7dd3012169c3f8dba3764cccd257cdf9e412f215/.github/workflows/eumserver-release-config.json#L21)):*
> ```JSON
>     ],
>     "ignore_labels": [
>         "wonfix",
> ```

this is missing a **"t"** in `wontfix`
___
*[`.github/workflows/eumserver_release.yml` line 61 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmJF9z7Vier8QhOcVv:-NKmJF9z7Vier8QhOcVw:b-ijs2l3) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L61)):*
> ```YAML
>           uses: actions/download-artifact@v3
>           with: 
>             name: eumserver-jar
> ```

can you add a short comment that we are referencing the `eumserver-jar` file that was uploaded in the `build_and_release` workflow?
___
*[`.github/workflows/eumserver_release.yml` line 67 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmJVL65KAat-wE5TP9:-NKmJVL65KAat-wE5TPA:bs718bt) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L67)):*
> ```YAML
>             cd docker
>             mv inspectit-ocelot-eum-server-${{ github.ref_name }}.jar inspectit-ocelot-eum-server.jar
>             ls
> ```

do we need the `ls` command or was this just for debugging?
___
*[`.github/workflows/eumserver_release.yml` line 84 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmJbm7D6QYlqtIj0bk:-NKmJbm7D6QYlqtIj0bl:b-2ou28x) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L84)):*
> ```YAML
>             context: .
>             push: true
>             tags: danipaniii/testing:${{ github.ref_name }}, danipaniii/testing:latest
> ```

just as a reminder: we need to change this address to `inspectit/inspectit-ocelot-eum-server` before merging into main
___
*[`docker/Dockerfile` line 3 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmK8hz5fE8WfJZVOL5:-NKmK8hz5fE8WfJZVOL6:bg6e1i8) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7dd3012169c3f8dba3764cccd257cdf9e412f215/docker/Dockerfile#L3)):*
> ```Dockerfile
> FROM openjdk:11-jre-slim
> 
> ADD ./docker/ /
> ```

can you add a short comment that we are referencing the `docker` dirctory that was created in the `publish_docker_image` workflow (or wherever the file was directory was created).

Will there be a `./docker/docker` directory? Or from which directory does the docker file gets built?

How could I build the docker image locally?



_Code quote (from .github/workflows/eumserver_release.yml):_
```YAML
docker/
```

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: all files reviewed, 5 unresolved discussions (waiting on @danipaniii)

**Comment by heiko-holz** [comment]
I didn't have any issues upgrading `cyclonedx`. Maybe the issue was rather with the URL of the boomerangjs-opentelemetry plugin that was also changed in the same commits?

**Comment by heiko-holz** [comment]
> I didn't have any issues upgrading cyclonedx. Maybe the issue was rather with the URL of the boomerangjs-opentelemetry plugin that was also changed in the same commits?

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @heiko-holz)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmLI1h7E45Aq5lIRgf:-NLKsHXW0m_U0OrR1Eui:b80h5te) (no related file):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I didn't have any issues upgrading `cyclonedx`. Maybe the issue was rather with the URL of the boomerangjs-opentelemetry plugin that was also changed in the same commits?
</blockquote></details>

The error was that instead of ```includeConfigs = ["runtimeClasspath"]```, I wrote ```includeConfigs += ["runtimeClasspath"]```

___
___
*[`.github/workflows/eumserver-release-config.json` line 21 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmHNVp3g56qACiSEs3:-NLKsO1m2ktHxELuhvwy:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7dd3012169c3f8dba3764cccd257cdf9e412f215/.github/workflows/eumserver-release-config.json#L21)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

this is missing a **"t"** in `wontfix`
</blockquote></details>

Done.
___
*[`.github/workflows/eumserver_release.yml` line 61 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmJF9z7Vier8QhOcVv:-NLKsjUI-IemVOM6amYH:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L61)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

can you add a short comment that we are referencing the `eumserver-jar` file that was uploaded in the `build_and_release` workflow?
</blockquote></details>

Done.
___
*[`.github/workflows/eumserver_release.yml` line 67 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmJVL65KAat-wE5TP9:-NLKsnZM1FJ6pM6Tnyix:bcqa2xs) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L67)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we need the `ls` command or was this just for debugging?
</blockquote></details>

This is for debugging to make sure that everything that we need  to build the docker image is in the directory.
I would probably leave it there, so that you don't always have to manually add it again when creating a release and you want to check if everything is in the directory.
___
*[`.github/workflows/eumserver_release.yml` line 84 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmJbm7D6QYlqtIj0bk:-NLKtP3l36UTo--4lxrs:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7bc34bd02db5c44bfb915751135c2bec7708162f/.github/workflows/eumserver_release.yml#L84)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

just as a reminder: we need to change this address to `inspectit/inspectit-ocelot-eum-server` before merging into main
</blockquote></details>

Done.
___
*[`docker/Dockerfile` line 3 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmK8hz5fE8WfJZVOL5:-NLKv67y4kopTT_drBAu:b-ooezzg) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7dd3012169c3f8dba3764cccd257cdf9e412f215/docker/Dockerfile#L3)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

can you add a short comment that we are referencing the `docker` dirctory that was created in the `publish_docker_image` workflow (or wherever the file was directory was created).

Will there be a `./docker/docker` directory? Or from which directory does the docker file gets built?

How could I build the docker image locally?
</blockquote></details>

I added a comment in the Dockerfile, hopefully answering all of those questions except the first one.

The docker directory is already existent in our project, so it does not have to be created, simply the contents of this directory will be added to the docker container to successfully build the image.

**Review by quandor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-:-NLPxBhh3hWvmC3Ap1JC:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

**Review by quandor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: all files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

**Review by quandor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: all files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

___
*[`docker/Dockerfile` line 3 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-NKmK8hz5fE8WfJZVOL5:-NLPzhFzDTi4WUKW39sm:b-ffeo8v) ([raw file](https://github.com/inspectit/inspectit-ocelot-eum-server/blob/7dd3012169c3f8dba3764cccd257cdf9e412f215/docker/Dockerfile#L3)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I added a comment in the Dockerfile, hopefully answering all of those questions except the first one.

The docker directory is already existent in our project, so it does not have to be created, simply the contents of this directory will be added to the docker container to successfully build the image.
</blockquote></details>

The build instructions should be in the README, too.

**Review by Dimi-Ma — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21#-:-NLQmw4863h2yp-jqjb6:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

**Review by Dimi-Ma — APPROVED** [review]
> Dismissed @heiko-holz from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot-eum-server/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

**Pull request merged**
